name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Print ENV
      run: env
    
    - name: 'Find & Replace'
      uses: warrenbuckley/Token-Replace-Action@releases/v1
      with:
        find: '{{MyPlaceholder}}'
        replace: 'HELLO WORLD'
